-- ==========================================================
-- SKEMA BASIS DATA MYSQL HOSTINGER UNTUK SISTEM GAP.SITE CRM
-- PT GAP Consulting / PT Tri Sinar Purnama
-- ==========================================================
-- Petunjuk Import Hostinger:
-- 1. Buka hPanel Hostinger -> Databases -> phpMyAdmin
-- 2. Pilih nama database Anda (contoh: u123456789_crm)
-- 3. Klik tab "Import" di bagian atas phpMyAdmin
-- 4. Pilih file ini (.sql) lalu klik "Go / Kirim"
-- ==========================================================

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+07:00";

-- 1. TABEL UTAMA: PROYEK CRM
CREATE TABLE IF NOT EXISTS `crm_projects` (
  `id` VARCHAR(100) NOT NULL PRIMARY KEY,
  `code` VARCHAR(50) DEFAULT NULL,
  `client_name` VARCHAR(255) DEFAULT NULL,
  `stage` VARCHAR(50) DEFAULT NULL,
  `status` VARCHAR(50) DEFAULT NULL,
  `kbli_code` VARCHAR(50) DEFAULT NULL,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_stage` (`stage`),
  INDEX `idx_client` (`client_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. TABEL KAS & TRANSAKSI
CREATE TABLE IF NOT EXISTS `crm_transactions` (
  `id` VARCHAR(100) NOT NULL PRIMARY KEY,
  `transaction_number` VARCHAR(100) DEFAULT NULL,
  `type` VARCHAR(20) DEFAULT NULL,
  `category` VARCHAR(100) DEFAULT NULL,
  `amount_idr` BIGINT DEFAULT 0,
  `date` VARCHAR(20) DEFAULT NULL,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_date` (`date`),
  INDEX `idx_type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. TABEL PIUTANG & INVOICE
CREATE TABLE IF NOT EXISTS `crm_receivables` (
  `id` VARCHAR(100) NOT NULL PRIMARY KEY,
  `invoice_number` VARCHAR(100) DEFAULT NULL,
  `client_name` VARCHAR(255) DEFAULT NULL,
  `total_amount` BIGINT DEFAULT 0,
  `paid_amount` BIGINT DEFAULT 0,
  `status` VARCHAR(50) DEFAULT NULL,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. TABEL PAJAK & KEPATUHAN
CREATE TABLE IF NOT EXISTS `crm_tax_obligations` (
  `id` VARCHAR(100) NOT NULL PRIMARY KEY,
  `tax_type` VARCHAR(50) DEFAULT NULL,
  `title` VARCHAR(255) DEFAULT NULL,
  `amount` BIGINT DEFAULT 0,
  `status` VARCHAR(50) DEFAULT NULL,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. TABEL PENGGAJIAN (PAYROLL)
CREATE TABLE IF NOT EXISTS `crm_payroll` (
  `id` VARCHAR(100) NOT NULL PRIMARY KEY,
  `employee_name` VARCHAR(255) DEFAULT NULL,
  `period` VARCHAR(50) DEFAULT NULL,
  `net_salary` BIGINT DEFAULT 0,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_period` (`period`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. TABEL PROYEK PEMERINTAH (SP2D)
CREATE TABLE IF NOT EXISTS `crm_government_projects` (
  `id` VARCHAR(100) NOT NULL PRIMARY KEY,
  `project_name` VARCHAR(255) DEFAULT NULL,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. TABEL PROYEK RETAIL & SWASTA
CREATE TABLE IF NOT EXISTS `crm_retail_projects` (
  `id` VARCHAR(100) NOT NULL PRIMARY KEY,
  `project_name` VARCHAR(255) DEFAULT NULL,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. TABEL PINJAMAN & HUTANG BANK
CREATE TABLE IF NOT EXISTS `crm_bank_loans` (
  `id` VARCHAR(100) NOT NULL PRIMARY KEY,
  `loan_name` VARCHAR(255) DEFAULT NULL,
  `bank_name` VARCHAR(255) DEFAULT NULL,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 9. TABEL DISPOSISI TUGAS
CREATE TABLE IF NOT EXISTS `crm_dispositions` (
  `id` VARCHAR(100) NOT NULL PRIMARY KEY,
  `disposition_number` VARCHAR(100) DEFAULT NULL,
  `assignee_name` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(50) DEFAULT NULL,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 10. TABEL PENGGUNA & ANGGOTA TIM
CREATE TABLE IF NOT EXISTS `crm_team_members` (
  `id` VARCHAR(100) NOT NULL PRIMARY KEY,
  `username` VARCHAR(100) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `role` VARCHAR(50) DEFAULT NULL,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 11. TABEL PENGATURAN & MASTER DATA SISTEM
CREATE TABLE IF NOT EXISTS `crm_app_settings` (
  `setting_key` VARCHAR(100) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 12. TABEL SNAPSHOT CADANGAN LENGKAP (POINT-IN-TIME RECOVERY)
CREATE TABLE IF NOT EXISTS `crm_full_snapshots` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `snapshot_name` VARCHAR(255) DEFAULT NULL,
  `total_records` INT DEFAULT 0,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
